[package]
name = "ffetch"
version = "0.1.0"
edition = "2021"
authors = ["justin13888 <20733699+justin13888@users.noreply.github.com>"]
description = "Fast, featureful, cross-platform fetching tool written in Rust "
readme = "README.md"
repository = "https://github.com/justin13888/ffetch"
homepage = "https://github.com/justin13888/ffetch"
license = "MIT"
keywords = ["system", "cli", "fetch"]
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
console = "0.15.7"
directories = "5.0.1"
humansize = { version = "2.1.3", features = ["impl_style"] }
lazy_static = "1.4.0"
libmacchina = { version = "7.2.2", features = ["version"] }
serde = { version = "1.0.201", features = ["derive"] }
sysinfo = { version = "0.30.12", features = ["debug", "serde"] }
thiserror = "1.0.60"
toml = "0.8.12"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-core = "0.1.32"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "json", "local-time"] }

[profile.release]
lto = true
codegen-units = 1

[features]
openwrt = ["libmacchina/openwrt"]
